kind: pipeline
name: default

steps:
- name: build
  image: plutzilla/lescinskas.lt:jekyll
  environment:
    JEKYLL_ENV: production
  commands:
    - bundle exec jekyll build
  when:
    branches: [master]
    event: [push]

image_pull_secrets:
- docker_config
