---
kind: pipeline
type: docker
name: lescinskas.lt release

steps:
- name: Build
  image: plutzilla/jekyll:4.0.0
  environment:
    JEKYLL_ENV: production
  commands:
    - bundle exec jekyll build -s src -d _site
  when:
    branch: [master, do-cicd]
    event: [push]

- name: Minify
  image: node:13
  when:
    branch: [master, do-cicd]
    event: [push]
  commands:
    - npm install
    - npx gulp

- name: Publish to DockerHub
  image: plugins/docker
  when:
    branch: [master, do-cicd]
    event: [push]
  settings:
    repo: plutzilla/lescinskas.lt
    tags:
      - ${DRONE_COMMIT_SHA:0:8}
      - latest
    dockerfile: nginx.Dockerfile
    username:
      from_secret: DOCKERHUB_USERNAME
    password:
      from_secret: DOCKERHUB_TOKEN

- name: Authenticate to DigitalOcean
  image: digitalocean/doctl
  when:
    branch: [do-cicd]
    event: [push]
  environment:
    DIGITALOCEAN_ACCESS_TOKEN:
      from_secret: DIGITALOCEAN_ACCESS_TOKEN
  commands:
    - /app/doctl auth init --access-token $DIGITALOCEAN_ACCESS_TOKEN
    - /app/doctl k8s cluster kubeconfig show do-k8s-lescinskas-lt-cluster > .kubeconfig

- name: Deploy Helm Chart to Staging
  image: alpine/helm
  when:
    branch: [do-cicd]
    event: [push]
  commands:
    - helm upgrade --install --kubeconfig=.kubeconfig -f ./deploy/helm/beta-lescinskas-lt.values.yaml --set image.tag=${DRONE_COMMIT_SHA:0:8} beta-lescinskas-lt ./deploy/helm/lescinskas.lt
