kind: pipeline
name: lescinskas.lt release

steps:
- name: build
  image: plutzilla/lescinskas.lt:jekyll
  environment:
    JEKYLL_ENV: production
  commands:
    - bundle exec jekyll build
  when:
    branches: [master]
    event:
      - push
      - deployment

- name: minify
  image: plutzilla/lescinskas.lt:gulp
  when:
    branches: [master]
    event:
      - push
      - deployment
  commands:
    - npm install
    - gulp

- name: publish
  image: plugins/gcr
  when:
    branches: [master]
    event:
      - push
      - deployment
  settings:
    repo: lescinskas-lt/nginx-server
    tags:
      - ${DRONE_COMMIT_SHA:0:8}
      - latest
    registry: eu.gcr.io
    dockerfile: nginx.Dockerfile
    json_key:
      from_secret: google_container_registry

- name: deploy
  image: google/cloud-sdk
  when:
    branches: [master]
    event:
      - push
      - deployment
  commands:
    - echo $GOOGLE_KUBERNETES_ENGINE > /gke.json
    - gcloud auth activate-service-account --key-file=/gke.json
    - gcloud config set project lescinskas-lt
    - gcloud config set compute/zone europe-north1-a
    - gcloud container clusters get-credentials lescinskas-lt-web-cluster
    - kubectl set image deployment/beta-lescinskas-lt-deploy nginx-server=eu.gcr.io/lescinskas-lt/nginx-server:$${DRONE_COMMIT_SHA:0:8} --record

image_pull_secrets:
- docker_config
