kind: pipeline
name: default

steps:
- name: build
  image: plutzilla/lescinskas.lt:jekyll
  environment:
    JEKYLL_ENV: production
  commands:
    - bundle exec jekyll build
  when:
    branches: [master]
    event: [push]

- name: minify
  image: plutzilla/lescinskas.lt:gulp
  when:
    branches: [master]
    event: [push]
  commands:
    - npm install
    - gulp

- name: publish
  image: plugins/gcr
  when:
    branches: [master]
    event: [push]
  settings:
    repo: lescinskas-lt/nginx-server
    tags:
      - ${DRONE_COMMIT_SHA:0:8}
      - latest
    registry: eu.gcr.io
    dockerfile: nginx.Dockerfile
    json_key:
      from_secret: google_container_registry

image_pull_secrets:
- docker_config
