kind: pipeline
name: lescinskas.lt release

steps:
- name: build
  image: plutzilla/jekyll:4.0.0
  environment:
    JEKYLL_ENV: production
  commands:
    - bundle exec jekyll build -s src -d _site
  when:
    branches: [master]
    event:
      - push

- name: minify
  image: node:13
  when:
    branches: [master]
    event:
      - push
  commands:
    - npm install
    - npx gulp

- name: publish
  image: plugins/gcr
  when:
    branches: [master]
    event:
      - push
  settings:
    repo: lescinskas-lt/nginx-server
    tags:
      - ${DRONE_COMMIT_SHA:0:8}
      - latest
    registry: eu.gcr.io
    dockerfile: nginx.Dockerfile
    json_key:
      from_secret: google_container_registry

- name: deploy to beta
  image: google/cloud-sdk
  when:
    branches: [master]
    event:
      - push
  commands:
    - echo $${GKE_BASE64} | base64 -d > gke.json
    - gcloud auth activate-service-account --key-file=gke.json
    - gcloud config set project lescinskas-lt
    - gcloud config set compute/zone europe-north1-a
    - gcloud container clusters get-credentials lescinskas-lt-web-cluster
    - kubectl set image deployment/beta-lescinskas-lt-deploy nginx-server=eu.gcr.io/lescinskas-lt/nginx-server:$${IMAGE_TAG} --record
  environment:
    GKE_BASE64:
      from_secret: gke_base64
    IMAGE_TAG: ${DRONE_COMMIT_SHA:0:8}

- name: deploy to production
  image: google/cloud-sdk
  when:
    branches: [master]
    event: promote
    target: production
  commands:
    - echo $${GKE_BASE64} | base64 -d > gke.json
    - gcloud auth activate-service-account --key-file=gke.json
    - gcloud config set project lescinskas-lt
    - gcloud config set compute/zone europe-north1-a
    - gcloud container clusters get-credentials lescinskas-lt-web-cluster
    - kubectl set image deployment/lescinskas-lt-deploy nginx-server=eu.gcr.io/lescinskas-lt/nginx-server:$${IMAGE_TAG} --record
  environment:
    GKE_BASE64:
      from_secret: gke_base64
    IMAGE_TAG: ${DRONE_COMMIT_SHA:0:8}

image_pull_secrets:
- docker_config
