---
kind: pipeline
type: docker
name: lescinskas.lt release

steps:

- name: Authenticate to DigitalOcean (deployment)
  image: digitalocean/doctl
  when:
    # ref: [refs/tags/*]
    event: promote
    target: production
  environment:
    DIGITALOCEAN_ACCESS_TOKEN:
      from_secret: DIGITALOCEAN_ACCESS_TOKEN
  commands:
    - /app/doctl auth init --access-token $DIGITALOCEAN_ACCESS_TOKEN
    - /app/doctl k8s cluster kubeconfig show do-k8s-lescinskas-lt-cluster > .kubeconfig

- name: Deploy Helm Chart to Production
  image: alpine/helm
  when:
    # ref: [refs/tags/*]
    event: promote
    target: production
  commands:
    - helm upgrade --install --kubeconfig=.kubeconfig -f ./deploy/helm/www-lescinskas-lt.values.yaml --set image.tag=0.1.1 www-lescinskas-lt ./deploy/helm/lescinskas.lt
