# Site settings
title: lescinskas.lt
email: paulius.lescinskas@gmail.com
description: "Paulius Leščinskas weblog"
baseurl: ""
url: "https://lescinskas.lt"
twitter_username: lescinskas
facebook_username:  paulius.lescinskas
linkedin_username: pluton
google_analytics_id: UA-771978-2
disqus_sitename: lescinskas

date_format: "%B %e, %Y"
date_format_archive: "%B %e"

# Build settings
markdown: kramdown
permalink: /blog/:year/:month/:day/:title/

exclude: ['node_modules', 'nbproject', 'gulpfile.js', '.gitignore', 'package.json', 'README.md']
