version: '3'

services:
  jekyll:
    image: jekyll/minimal:4
    volumes:
      - .:/srv/jekyll
    ports:
      - '8080:4000'
    command: ['jekyll', 'serve', '-s', 'src', '-d', '_site', '--drafts', '--watch', '-H', '0.0.0.0', '-P', '4000']
