controller:
  replicaCount: 2
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: app
            operator: In
            values:
            - "lescinskas-lt-nginx-ingress-nginx-ingress"
        topologyKey: "kubernetes.io/hostname"
