replicaCount: 2

image:
  repository: plutzilla/lescinskas.lt
  tag: latest
  pullPolicy: IfNotPresent

ingress:
  enabled: true
  annotations: {}
  hosts:
    - host: lescinskas.lt
      paths:
        - path: '/'
          pathType: ImplementationSpecific
    - host: www.lescinskas.lt
      paths:
        - path: '/'
          pathType: ImplementationSpecific
  tls: []
