name: Build lescinskas.lt website

on:
  workflow_call:

jobs:
  build:
    name: Build Jekyll website
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - run: mkdir src/.jekyll-cache
      - run: chmod 0777 src/.jekyll-cache
      - run: mkdir _site
      - run: chmod 0777 _site
      - name: Build using Jekyll Docker container
        uses: docker://jekyll/minimal:4
        with:
          args: jekyll build -s src -d _site --trace
        env:
          JEKYLL_ENV: production
      - name: Store built website
        uses: actions/upload-artifact@v3
        with:
          name: website-build
          path: _site
