name: Minify lescinskas.lt website

on:
  workflow_call:

jobs:
  minify:
    name: Minify website files
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Download built artifact
        uses: actions/download-artifact@v3
        with:
          name: website-build
          path: _site
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Cache Node modules
        uses: actions/cache@v2
        env:
          cache-name: node-module-cache
        with:
          path: ~/.npm
          key: ${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
      - run: npm install
      - run: npx gulp
      - name: Store minified website
        uses: actions/upload-artifact@v3
        with:
          name: website-minified
          path: _site
