name: Build and deploy lescinskas.lt website

on:
  push:
    branches: [cicd-with-actions]

jobs:
  build:
    name: Build Jekyll website
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: docker://jekyll/minimal:4
        with:
          args: jekyll build -s src -d _site --trace
