name: Build lescinskas.lt website

on:
  push:
    branches: [cicd-with-actions]

jobs:
  build:
    name: Build Jekyll website
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - run: mkdir src/.jekyll-cache
      - run: chmod 0777 src/.jekyll-cache
      - run: mkdir _site
      - run: chmod 0777 _site
      - name: Build using Jekyll Docker container
        uses: docker://jekyll/minimal:4
        with:
          args: jekyll build -s src -d _site --trace
      - name: Store built website
        uses: actions/upload-artifact@v2
        with:
          name: website-build
          path: _site
  minify:
    name: Minify website files
    needs: build
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Download built artifact
        uses: actions/download-artifact@v2
        with:
          name: website-build
          path: _site
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Cache Node modules
        uses: actions/cache@v2
        env:
          cache-name: node-module-cache
        with:
          path: ~/.npm
          key: ${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
      - run: npm install
      - run: npx gulp
