name: Build and deploy lescinskas.lt website

on:
  push:
    branches: [cicd-with-actions]

jobs:
  build:
    name: Build Jekyll website
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - run: mkdir src/.jekyll-cache
      - run: chmod 0777 src/.jekyll-cache
      - run: mkdir _site
      - run: chmod 0777 _site
      - name: Build using Jekyll Docker container
        uses: docker://jekyll/minimal:4
        with:
          args: jekyll build -s src -d _site --trace
      - name: Store built website
        uses: actions/upload-artifact@v2
        with:
          name: website-build
          path: _site
  minify:
    name: Minify website files
    runs-on: ubuntu-20.04
    steps:
      - name: Download built artifact
        uses: actions/download-artifact@v2
        with:
          name: website-build
      - name: Setup Node
        uses: actions/setup-node
        with:
          node-version: 13
      - run: npm install
      - run: npx gulp
      - name: Store minified website
        uses: actions/upload-artifact@v2
        with:
          name: website-minified
