name: Build and deploy lescinskas.lt website

on:
  push:
    branches: [cicd-with-actions]

jobs:
  build:
    name: Build Jekyll website
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: docker://jekyll/minimal:4
        with:
          args: >
            mkdir src/.jekyll-cache &&
            chown  jekyll:jekyll src/.jekyll-cache &&
            mkdir _site &&
            chown jekyll:jekyll _site &&
            jekyll build -s src -d _site --trace
