name: Deploy lescinskas.lt website to production

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  deploy-to-production:
    name: Deploy to production
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_TOKEN }}
      - name: Get kubeconfig
        run: doctl k8s cluster kubeconfig show do-k8s-lescinskas-lt-cluster > .kubeconfig
      - name: Start deployment
        uses: tallyb/deployments@master
        id: deployment
        with:
          step: start
          token: ${{ secrets.GITHUB_TOKEN }}
          env: production
      - name: Deploy using helm
        uses: docker://alpine/helm:3.3.1
        with:
          # entrypoint: helm
          args: >
            upgrade
            --install
            --kubeconfig=.kubeconfig
            -f ./deploy/helm/www-lescinskas-lt.values.yaml
            --set image.repository=ghcr.io/plutzilla/lescinskas-lt-website
            --set image.tag=${{ github.sha }}
            www-lescinskas-lt
            ./deploy/helm/lescinskas.lt
      - name: Update deployment status
        uses: tallyb/deployments@master
        if: always()
        with:
          step: finish
          token: ${{ secrets.GITHUB_TOKEN }}
          status: ${{ job.status }}
          deployment_id: ${{ steps.deployment.outputs.deployment_id }}
          env_url: https://lescinskas.lt
