name: Verify website build

on:
  push:
    branches-ignore:
      - "master"

jobs:
  build:
    uses: ./.github/workflows/_build.yml
  minify:
    uses: ./.github/workflows/_minify.yml
    needs: build
